"""

Revision ID: 25a38b6e2f87
Revises: cc780e201daa
Create Date: 2023-06-12 20:33:55.177456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a38b6e2f87'
down_revision = 'cc780e201daa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('coin_name', sa.Text(), nullable=False),
    sa.Column('estimated_delivery_price', sa.Numeric(), nullable=False),
    sa.Column('index_price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickers'))
    )
    op.drop_table('coins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('coin_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('estimated_delivery_price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('index_price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_coins')
    )
    op.drop_table('tickers')
    # ### end Alembic commands ###
