"""

Revision ID: 533c458359e3
Revises: 
Create Date: 2023-06-13 14:51:14.203909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533c458359e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('coin_name', sa.Text(), nullable=False),
    sa.Column('estimated_delivery_price', sa.Numeric(), nullable=False),
    sa.Column('index_price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickers')
    # ### end Alembic commands ###
