"""

Revision ID: 6bc5d5a34512
Revises: 
Create Date: 2023-06-12 17:57:45.049314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc5d5a34512'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_coin',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('coin_name', sa.Text(), nullable=False),
    sa.Column('estimated_delivery_price', sa.Numeric(), nullable=False),
    sa.Column('index_price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_btc_coin'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('btc_coin')
    # ### end Alembic commands ###
