"""1

Revision ID: 773ed70e56d3
Revises: e2648c9c8cdb
Create Date: 2023-06-10 05:16:00.939650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773ed70e56d3'
down_revision = 'e2648c9c8cdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
