"""

Revision ID: 898e439265a3
Revises: 22a95eaa0067
Create Date: 2023-06-10 01:50:19.777728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898e439265a3'
down_revision = '22a95eaa0067'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_coin',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('estimated_delivery_price', sa.Numeric(), nullable=False),
    sa.Column('index_price', sa.Numeric(), nullable=False),
    sa.Column('current_time', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_btc_coin'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('btc_coin')
    # ### end Alembic commands ###
