"""

Revision ID: cc780e201daa
Revises: 9a1a83345d41
Create Date: 2023-06-12 20:33:19.745921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc780e201daa'
down_revision = '9a1a83345d41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('coin_name', sa.Text(), nullable=False),
    sa.Column('estimated_delivery_price', sa.Numeric(), nullable=False),
    sa.Column('index_price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coins'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coins')
    # ### end Alembic commands ###
