"""

Revision ID: e2648c9c8cdb
Revises: d7d82cbe2d7c
Create Date: 2023-06-10 05:13:25.624229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2648c9c8cdb'
down_revision = 'd7d82cbe2d7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
